services:
  db:
    image: postgis/postgis:17-master
    container_name: postgis
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hotspotdb
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
